# Generated by Django 3.2.18 on 2023-06-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('users', '0002_auto_20230624_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shipping_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.wishlist'),
        ),
    ]
