# Generated by Django 3.2.18 on 2023-06-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wishlist',
        ),
    ]
