# Generated by Django 3.2.18 on 2023-07-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20230714_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_amount',
            field=models.FloatField(default=0.0, verbose_name='Total amount'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
