# Generated by Django 3.2.18 on 2023-07-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20230715_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Total amount'),
        ),
    ]
