# Generated by Django 3.2.18 on 2023-07-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_amount',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Total amount'),
        ),
    ]
