# Generated by Django 3.2.18 on 2023-06-24 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_customer', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_product_variation', to='products.productvariation', verbose_name='Product varitaion'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvariation_product', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product_attribute_values',
            field=models.ManyToManyField(related_name='productvariation_attribute_value', to='products.AttributeValue', verbose_name='Attribute value'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product_tags',
            field=models.ManyToManyField(related_name='productvariation_tag', to='products.Tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimage_productvariation', to='products.productvariation', verbose_name='Product variation'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='products.brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='products.category', verbose_name='Parent comment'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributevalue_attribute', to='products.attribute', verbose_name='Attribute'),
        ),
    ]
