# Generated by Django 3.2.18 on 2023-06-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230627_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_active',
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
