# Generated by Django 3.2.18 on 2023-06-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230627_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.discount'),
        ),
    ]
