# Generated by Django 3.2.18 on 2023-06-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariation_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
